### ISSUE TITLE
"Associate" staff and affiliations

### ISSUE THREAD

**Issue by barryrowlingson** [chicas-lancaster/websource#27]
We want to keep the main list of staff on the people page as just core CHICAS staff based in MED.  But we still want other people to have a CHICAS visibility.

proposal:

* Create a new group called "Associate and Visiting Staff".
* Put current visiting staff and non-FHM Lancaster staff and associated staff in that group.
* For each person in that group, add:
  *  an `affiliation: ` metadata item with the name of their home institution
  *  an `affiliation_link:` metadata item with a URL of their home institution (optional)
* On the people page, list the institution in small print under their name, as a hyperlink.
* On the person's page, put the affiliation and link in the sidebar.

**Comment by peterjohndiggle** [comment]
Sounds a good idea – cheers, Peter

**Comment by barryrowlingson** [comment]
Now done and live.
